In [ ]:
from tensorflow.keras.datasets import mnist
from matplotlib import pyplot as plt

In [ ]:
import keras
from keras.datasets import mnist
#load mnist dataset

In [ ]:
data = mnist.load_data()

11490434/11490434 [==============================] - 1s 0us/step


In [ ]:
(X_train, y_train), (X_test, y_test) = data

In [ ]:
X_train.shape


(60000, 28, 28)

In [ ]:
X_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [ ]:
train_norm = X_train / 255.0
test_norm = X_test/ 255.0

In [ ]:
from keras import Sequential

In [ ]:
model = Sequential()

In [ ]:
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Dense
from keras.layers import Flatten
from keras.optimizers import SGD

In [ ]:
model.add(Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_uniform', input_shape=(28, 28, 1)))


In [ ]:
model.add(MaxPooling2D((2, 2)))

In [ ]:
model.add(Flatten())
model.add(Dense(100, activation='relu', kernel_initializer='he_uniform'))
model.add(Dense(1, activation='softmax'))
#compile model
opt = SGD(learning_rate=0.01, momentum=0.9)
model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
trainX = X_train.reshape((X_train.shape[0], 28, 28, 1)).astype('float32')
testX = X_test.reshape((X_test.shape[0], 28, 28, 1)).astype('float32')

In [ ]:
trainX

array([[[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
 

In [ ]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [ ]:
model.fit(X_train, y_train, epochs=10, batch_size=32)

Epoch 1/10
1875/1875 [==============================] - 49s 26ms/step - loss: nan - accuracy: 0.0987
Epoch 2/10
1875/1875 [==============================] - 38s 20ms/step - loss: nan - accuracy: 0.0987
Epoch 3/10
1875/1875 [==============================] - 38s 20ms/step - loss: nan - accuracy: 0.0987
Epoch 4/10
1875/1875 [==============================] - 38s 20ms/step - loss: nan - accuracy: 0.0987
Epoch 5/10
1875/1875 [==============================] - 39s 21ms/step - loss: nan - accuracy: 0.0987
Epoch 6/10
1875/1875 [==============================] - 38s 20ms/step - loss: nan - accuracy: 0.0987
Epoch 7/10
1875/1875 [==============================] - 38s 20ms/step - loss: nan - accuracy: 0.0987
Epoch 8/10
1875/1875 [==============================] - 39s 21ms/step - loss: nan - accuracy: 0.0987
Epoch 9/10
1875/1875 [==============================] - 39s 21ms/step - loss: nan - accuracy: 0.0987
Epoch 10/10
1875/1875 [==============================] - 38s 20ms/step - loss: nan - accura

In [ ]:
trainX = X_train.reshape((X_train.shape[0], 28, 28, 1)).astype('float32')
testX = X_test.reshape((X_test.shape[0], 28, 28, 1)).astype('float32')